apiVersion: v1
kind: Service
metadata:
  name: myapp-service #name of the service
spec:
  type: NodePort #Type of service we are creating
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004
  selector: #to connect to the pod
    app: myapp


